/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppAuthForgotPasswordRouteImport } from './routes/app/auth/forgot-password'
import { Route as AppContactCustomerIndexRouteImport } from './routes/app/contact/customer/index'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAuthForgotPasswordRoute = AppAuthForgotPasswordRouteImport.update({
  id: '/app/auth/forgot-password',
  path: '/app/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppContactCustomerIndexRoute = AppContactCustomerIndexRouteImport.update({
  id: '/app/contact/customer/',
  path: '/app/contact/customer/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/app/auth/forgot-password': typeof AppAuthForgotPasswordRoute
  '/app/contact/customer/': typeof AppContactCustomerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/app/auth/forgot-password': typeof AppAuthForgotPasswordRoute
  '/app/contact/customer': typeof AppContactCustomerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/app/auth/forgot-password': typeof AppAuthForgotPasswordRoute
  '/app/contact/customer/': typeof AppContactCustomerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/app/auth/forgot-password'
    | '/app/contact/customer/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/app/auth/forgot-password' | '/app/contact/customer'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/app/auth/forgot-password'
    | '/app/contact/customer/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  AppAuthForgotPasswordRoute: typeof AppAuthForgotPasswordRoute
  AppContactCustomerIndexRoute: typeof AppContactCustomerIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/auth/forgot-password': {
      id: '/app/auth/forgot-password'
      path: '/app/auth/forgot-password'
      fullPath: '/app/auth/forgot-password'
      preLoaderRoute: typeof AppAuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/contact/customer/': {
      id: '/app/contact/customer/'
      path: '/app/contact/customer'
      fullPath: '/app/contact/customer/'
      preLoaderRoute: typeof AppContactCustomerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  AppAuthForgotPasswordRoute: AppAuthForgotPasswordRoute,
  AppContactCustomerIndexRoute: AppContactCustomerIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
